### ISSUE TITLE
Brio vanishing when put into window with other applications

### ISSUE THREAD

**Issue by lyricscientia** [AsgardXIV/Brio#1]
Specifically currently Ktisis but Ktisis was able to dock with other windows before, thus leading me to believe it's a Brio issue.

It's as simple as it sounds I think? Upon putting them into a window together, the app vanishes entirely. I've tried restarting, I've tried disabling then reenabling, I've tried deleting it from the app folders completely, I've trued only opening Ktisis, I've tried only enabling Brio, and nothing brings them back.

**Comment by AsgardXIV** [comment]
I see the issue and it will be fixed in the next release.
Temporarily you can disable docking in /xlsettings and it will recover them.

Then you can re-enable and just not dock Brio until the next release.

**Comment by AsgardXIV** [comment]
This should be fixed in v0.1.5.0.
