### ISSUE TITLE
Fem Miqo'te Animations with Ear Movement don't scrub properly

### ISSUE THREAD

**Issue by z-nanami-chiaki** [AsgardXIV/Brio#11]
Vanilla emotes on Fem Miqo'te that have ear movements don't play properly when played through the Animation dropdown.
Animations that have no ear movements play fine.

https://github.com/AsgardXIV/Brio/assets/121415806/1c710e0a-b0de-4597-ad47-f28631728257

**Comment by AsgardXIV** [comment]
Fixed in 0.2
