### ISSUE TITLE
Glamoured minion snaps appearance when enabling wetness

### ISSUE THREAD

**Issue by TigerNef** [AsgardXIV/Brio#16]
I figured I would inform of this whether it's a problem or not so perhaps others don't commit the same mistake as me or maybe if it has a possible solution it can be addressed.

> Problem: I glamoured a minion to a "human" appearance outside GPOSE mode and while in GPOSE using Brio I tried adding wetness with the wet effect of the advanced adjustments of Brio and it snaps the minion back to it's vanilla form.

I tested glamouring the minion to "human" with Brio (inside GPOSE of course) and this won't happen so I do suggest using this method instead of Glamourer for multi actor pictures. That way your actors won't snap their appearances.

**Comment by AsgardXIV** [comment]
Yeh, this is expected unfortunately. Due to the way glamourer works.
When you make a change in Brio, you are basically overwriting whatever change you made in Glamourer.
