### ISSUE TITLE
Growing Fingers

### ISSUE THREAD

**Issue by OriginalGamer1** [AsgardXIV/Brio#17]
If I start manipulating fingers after loading a pose they slowly elongate after every move. Only seems to be a problem after loading a pose, because if I click "reset pose" it stops happening. 

I've linked a short video showing the problem below.
https://github.com/AsgardXIV/Brio/assets/156396563/3fc0de9d-862d-4d4e-aaa6-4fa530697cb9

**Comment by StoiaCode** [comment]
FYI this is a known issue right now. Some people are trying to figure out whats going on, but we dont have any ETA :)

**Comment by Minmoose** [comment]
Apologies for the delay, this should be fixed with 0.2.2.0, if it is not, please make a new issue.
