### ISSUE TITLE
Cannot click setting icon under using lager fonts

### ISSUE THREAD

**Issue by Cyba-Aquiya** [AsgardXIV/Brio#3]
When the Global Font Scale of Dalamud is set larger than 14pt, the info, setting, and minimize icons in Brio are too close to each other, so the setting cannot be opened.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/123396618/214108763-0440325d-c258-40ab-947e-bf6275e21ef8.png">

**Comment by AsgardXIV** [comment]
This will be fixed in the next release.
Thanks for reporting it!

**Comment by AsgardXIV** [comment]
Should be resolves in v0.1.6.1. Please reoopen if you still have issues.
