### ISSUE TITLE
Search icon, etc. in Animations do not appear enough.

### ISSUE THREAD

**Issue by Cyba-Aquiya** [AsgardXIV/Brio#4]
Search icon, etc. in Animations do not appear. Icons do not appear, especially when fonts larger than 14pt are set.
The attached screen is in 14pt font.

(I know you are busy, so don't rush.)
![image](https://user-images.githubusercontent.com/123396618/214914728-e9bf289e-b71a-4756-8fd7-f3a28737d2ce.png)

**Comment by AsgardXIV** [comment]
Should be resolved in v0.1.8.2
