### ISSUE TITLE
Cannot open use Brio in game

### ISSUE THREAD

**Issue by NMDWSMAA** [AsgardXIV/Brio#5]
I notice I cannot use Brio today, I type the /brio several times but nothing happens. I've also tried to install and uninstall the plugin, it just didn't work anymore

**Comment by AsgardXIV** [comment]
If you are playing on the Worldwide servers the new version, v0.1.8.6 should work correctly with Patch 6.4.
If you are on the Chinese or Korean servers (6.3) you'd need to use the older v0.1.8.4 build somehow.
